### ISSUE TITLE
Consider fetching fixtures from same directory level spec checkout

### ISSUE THREAD

**Issue by andrew-gardener** [IMSGlobal/caliper-python#214]
Instead of checking out `caliper-spec` into the `tests` sub folder, it might be easier to expect it to be checked out at the same directory level as the `caliper-python` project.

ex: change 
https://github.com/IMSGlobal/caliper-python/blob/develop/tests/util.py#L40
to 
`_FIXTURE_BASE_DIR = os.path.join(TESTDIR, '..', '..', _FIXTURE_PREFIX)`

I think it makes it a bit easier to test (especially if your already working on the spec/other implementation libraries). Currently `caliper-php` and `caliper-js` do this but `caliper-ruby` does not (not sure about the other ones)

**Comment by ViktorHaag** [comment]
I made the conscious choice not to, so that you'd explicitly have a copy of the fixtures to test against that you could manage _independently_ of a copy of the spec to work on otherwise. I'll think more about this to see if there's a good solution but would like to leave the default state being "all contained within the package/repo dir".
